dependencies {

    // Core Spring Boot Functionality
    implementation('org.springframework.boot:spring-boot-starter-web') {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-tomcat'
    }
    implementation 'org.springframework.boot:spring-boot-starter-webflux'  // lightweight dispatcher

    //AWS Lambda Support
    implementation 'com.amazonaws.serverless:aws-serverless-java-container-springboot3'
    implementation 'com.amazonaws:aws-lambda-java-core'
    implementation 'com.amazonaws:aws-lambda-java-events'


    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.bootJar {
    enabled = false
}

tasks.jar {
    enabled = true
}

shadowJar {
    archiveFileName = 'solastra.jar'
    mergeServiceFiles()

    append('META-INF/spring.handlers')
    append('META-INF/spring.schemas')
    append('META-INF/spring.tooling')
    append('META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports')

    transform(com.github.jengelman.gradle.plugins.shadow.transformers.PropertiesFileTransformer) {
        paths = ['META-INF/spring.factories']
        mergeStrategy = "append"
    }

    manifest {
        attributes 'Main-Class': 'com.solastra.Api'
        attributes 'Start-Class': 'com.solastra.Api'
    }

    exclude 'META-INF/*.SF'
    exclude 'META-INF/*.DSA'
    exclude 'META-INF/*.RSA'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.register('buildZip', Zip) {
    dependsOn shadowJar
    from(zipTree(shadowJar.archiveFile))
    archiveFileName = 'solastra.zip'
    destinationDirectory = layout.buildDirectory.dir("distributions")
}

tasks.register('buildLocal') {
    group = "build"
    description = "Build application for localstack environment"
    dependsOn buildZip
}
