spring.application.name=solastra-api

# WebFlux configuration
spring.codec.max-in-memory-size=10MB

# WebFlux multipart configuration
spring.webflux.multipart.max-in-memory-size=10MB
spring.webflux.multipart.max-parts=10
spring.webflux.multipart.max-disk-usage-per-part=10MB
