services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-solastra
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,iam,apigateway,s3
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/var/lib/localstack
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=30
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.localstack:/var/lib/localstack"
